### ISSUE TITLE
Plotly import error with plotly>=4

### ISSUE THREAD

**Issue by jbegaint** [Cadene/bootstrap.pytorch#11]
I'm getting the following error when installing the latest plotly version:
```
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 
```
It seems version 4 and onward breaks backward compatibility with plotly 3.10

There's a migration guide (https://plot.ly/python/v4-migration/), but in the meantime maybe you could pin the plotly version in the requirements.txt ?

**Comment by MicaelCarvalho** [comment]
I had the same problem when I upgraded my environment a few weeks ago. Fixed it locally and made a self-note to send the patch to bootstrap, but ended up not having the time to do so. I'm pushing changes now.
