### ISSUE TITLE
Add Pylint and Black?

### ISSUE THREAD

**Issue by Cadene** [Cadene/bootstrap.pytorch#20]
[Pylint](https://www.pylint.org)

[Black](https://black.readthedocs.io/en/stable/installation_and_usage.html)

And integrate Pylint with the tests.

**Comment by jbegaint** [comment]
[isort](https://github.com/timothycrosley/isort) for cleaning the imports could also be useful no ?

(it's also quite easy to integrate pylint/black/isort in git hooks)
